version: '3'
volumes:
  mysql_db:
    external: true
services:
  redis:
    image: redis:alpine
    command: redis-server
    container_name: redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=template
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - "3306:3306"
  web:
    build: ./
    command: yarn run dev
    ports:
      - "80:3000"
    volumes:
      - ./app:/code/app
      - ./public:/code/public
    tty: true
    links:
      - mysql
      - redis
    environment:
      NODE_ENV:
networks:
  default:
    external:
      name: local
